name: Deploy Budget

on: # на какие события запускать, какие ветки
  push: # событие
    branches: [ "main" ] # ветка
  # pull_request:
  #   branches: [ "main" ]

jobs: # задачи
  deploy:

    runs-on: ubuntu-latest # операционная система на которой будем запускать (ubuntu разновидность linux, наиболе часто стоит на серверах)

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.TIMEWEB_HOST }}
          username: ${{ secrets.TIMEWEB_USER_NAME }}
          key: ${{ secrets.TIMEWEB_PRIVATE_KEY }}
          script: |
            echo 'Deploying'
            cd /home/c/cn01455/budget 
            set -e
            git pull origin main
            /opt/php82/bin/php artisan down
            /opt/php82/bin/php composer.phar install --no-dev --optimize-autoloader
            /opt/php82/bin/php artisan migrate --force 
            /opt/php82/bin/php artisan config:cache
            /opt/php82/bin/php artisan view:cache
            /opt/php82/bin/php artisan event:cache
            /opt/php82/bin/php artisan route:cache
            /opt/php82/bin/php artisan up
          


          


